#!/usr/bin/env python3
"""Full analysis pipeline for particle classification datasets.

Runs dataset leak detection, per-class noise analysis, and training benchmark
in sequence, producing all results in a single centralized folder.

Usage:
    python run_full_analysis.py dataset
    python run_full_analysis.py dataset --dataset-name my_dataset --epochs 100
    python run_full_analysis.py dataset --real-test-dir dataset_real/test --wandb-offline
"""

import argparse
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent


def discover_classes(dataset_path: Path) -> list[str]:
    """Discover class names from subdirectories of train/."""
    train_dir = dataset_path / "train"
    return sorted(d.name for d in train_dir.iterdir() if d.is_dir())


def run_step(cmd: list[str], step_label: str) -> subprocess.CompletedProcess:
    """Run a subprocess and print its output in real time."""
    print(f"\n{'─' * 60}")
    print(f"  {step_label}")
    print(f"{'─' * 60}\n")
    result = subprocess.run(cmd, cwd=SCRIPT_DIR)
    return result


def write_summary(output_dir: Path, args, class_names: list[str],
                  leak_result: subprocess.CompletedProcess,
                  noise_results: dict[str, subprocess.CompletedProcess],
                  benchmark_result: subprocess.CompletedProcess | None):
    """Generate analysis_summary.md tying all results together."""
    md_path = output_dir / "analysis_summary.md"
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    with open(md_path, "w") as f:
        f.write("# Full Analysis Summary\n\n")
        f.write(f"> **Generated:** {now}\n\n")

        # Parameters
        f.write("## Parameters\n\n")
        f.write(f"| Parameter | Value |\n")
        f.write(f"|---|---|\n")
        f.write(f"| Dataset | `{Path(args.dataset).resolve()}` |\n")
        f.write(f"| Dataset name | `{args.dataset_name}` |\n")
        f.write(f"| Classes | {', '.join(f'`{c}`' for c in class_names)} |\n")
        f.write(f"| Similarity threshold | {args.similarity_threshold} |\n")
        f.write(f"| Epochs | {args.epochs} |\n")
        f.write(f"| Batch size | {args.batch_size} |\n")
        f.write(f"| Learning rate | {args.lr} |\n")
        f.write(f"| Seed | {args.seed} |\n")
        f.write(f"| Patience | {args.patience} |\n\n")

        # Step 1: Leaks
        f.write("## Step 1: Dataset Leak Detection\n\n")
        if leak_result.returncode == 0:
            f.write("**Result: PASSED** (no critical leaks)\n\n")
        else:
            f.write("**Result: CRITICAL LEAKS DETECTED** — pipeline aborted\n\n")
        f.write("See [leak_reports/summary.md](leak_reports/summary.md) for details.\n\n")

        # Step 2: Noise analysis
        f.write("## Step 2: Noise Analysis\n\n")
        f.write("| Split | Class | Status | Report |\n")
        f.write("|---|---|---|---|\n")
        for key, result in noise_results.items():
            split, cls = key.split("/")
            pdf_name = f"{split}_{cls}_Noise_Analysis.pdf"
            status = "Done" if result.returncode == 0 else f"FAILED (exit {result.returncode})"
            link = f"[PDF](noise_analysis/{pdf_name})" if result.returncode == 0 else "—"
            f.write(f"| {split} | {cls} | {status} | {link} |\n")
        f.write("\n")

        # Step 3: Benchmark
        f.write("## Step 3: Training & Benchmark\n\n")
        if benchmark_result is not None:
            if benchmark_result.returncode == 0:
                f.write("**Result: COMPLETED**\n\n")
                f.write(f"- Model saved to `benchmark/best_model.pth`\n")
                f.write(f"- Training metrics logged to W&B project `particle-benchmark`\n")
                f.write(f"- W&B run: `Conv1D-{args.dataset_name}-{args.run_id}`\n\n")
            else:
                f.write(f"**Result: FAILED** (exit code {benchmark_result.returncode})\n\n")
        else:
            f.write("**Skipped** (pipeline aborted due to critical leaks)\n\n")

        f.write("---\n\n")
        f.write("*Generated by `run_full_analysis.py`*\n")


def main():
    parser = argparse.ArgumentParser(
        description="Full analysis pipeline: leak detection → noise analysis → benchmark.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python run_full_analysis.py dataset\n"
            "  python run_full_analysis.py dataset --dataset-name synthetic_v2 --epochs 100\n"
            "  python run_full_analysis.py dataset --real-test-dir dataset_real/test --wandb-offline\n"
        ),
    )
    # Dataset args
    parser.add_argument("dataset", type=str, nargs="?", default="dataset",
                        help="Path to dataset root (default: dataset)")
    parser.add_argument("--dataset-name", type=str, default=None,
                        help="Dataset name for W&B and output folder (default: dataset folder name)")

    # dataset_leaks.py args
    parser.add_argument("--similarity-threshold", type=float, default=0.99,
                        help="Cosine similarity threshold for near-duplicates (default: 0.99)")

    # analyze_noise.py args
    parser.add_argument("--fs", type=float, default=2_000_000,
                        help="Sampling frequency in Hz (default: 2000000)")
    parser.add_argument("--segment", type=int, default=2500,
                        help="Segment length for noise analysis (default: 2500)")

    # benchmark.py args
    parser.add_argument("--real-test-dir", type=str, default=None,
                        help="Path to real test data directory")
    parser.add_argument("--epochs", type=int, default=150, help="Number of training epochs")
    parser.add_argument("--batch-size", type=int, default=32, help="Batch size")
    parser.add_argument("--lr", type=float, default=6e-4, help="Learning rate")
    parser.add_argument("--patience", type=int, default=0,
                        help="Early stopping patience (0 = disabled)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument("--run-id", type=str, default="run1", help="Run identifier for W&B naming")
    parser.add_argument("--wandb-offline", action="store_true", help="Run W&B in offline mode")
    parser.add_argument("--scheduler", choices=["none", "cosine", "plateau"], default="cosine",
                        help="LR scheduler: none, cosine, plateau (default: cosine)")

    args = parser.parse_args()

    dataset_path = Path(args.dataset)
    if args.dataset_name is None:
        args.dataset_name = dataset_path.name

    # ── Step 0: Validate & setup ──────────────────────────────────────────
    print("=" * 60)
    print("  FULL ANALYSIS PIPELINE")
    print("=" * 60)

    if not dataset_path.is_dir():
        sys.exit(f"ERROR: dataset path not found: {dataset_path}")
    if not (dataset_path / "train").is_dir():
        sys.exit(f"ERROR: missing train/ directory in {dataset_path}")
    if not (dataset_path / "test").is_dir():
        sys.exit(f"ERROR: missing test/ directory in {dataset_path}")

    class_names = discover_classes(dataset_path)
    if not class_names:
        sys.exit(f"ERROR: no class subdirectories found in {dataset_path / 'train'}")

    output_dir = Path(f"{args.dataset_name}_full_analysis")
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "noise_analysis").mkdir(parents=True, exist_ok=True)
    (output_dir / "benchmark").mkdir(parents=True, exist_ok=True)

    print(f"  Dataset:     {dataset_path.resolve()}")
    print(f"  Classes:     {class_names}")
    print(f"  Output:      {output_dir.resolve()}")
    print()

    pipeline_start = time.time()

    # ── Step 1: Dataset leak detection ────────────────────────────────────
    leak_cmd = [
        sys.executable, str(SCRIPT_DIR / "dataset_leaks.py"),
        str(dataset_path),
        "--report-dir", str(output_dir / "leak_reports"),
        "--similarity-threshold", str(args.similarity_threshold),
    ]
    leak_result = run_step(leak_cmd, "[1/3] Dataset Leak Detection")

    if leak_result.returncode != 0:
        print("\n" + "=" * 60)
        print("  PIPELINE ABORTED — CRITICAL LEAKS DETECTED")
        print("=" * 60)
        print(f"  Review: {(output_dir / 'leak_reports' / 'summary.md').resolve()}")
        print(f"  Fix leaks with: python fix_leaks.py")
        print(f"  Then re-run this pipeline.")

        write_summary(output_dir, args, class_names, leak_result, {}, None)
        sys.exit(1)

    # ── Step 2: Noise analysis (both splits × all classes) ────────────────
    splits = ["train", "test"]
    noise_results = {}
    total_noise = len(splits) * len(class_names)
    noise_idx = 0

    for split in splits:
        for cls in class_names:
            noise_idx += 1
            class_dir = dataset_path / split / cls
            if not class_dir.is_dir():
                print(f"  WARNING: {class_dir} not found, skipping")
                continue

            pdf_path = output_dir / "noise_analysis" / f"{split}_{cls}_Noise_Analysis.pdf"
            noise_cmd = [
                sys.executable, str(SCRIPT_DIR / "analyze_noise.py"),
                str(class_dir),
                "--output", str(pdf_path),
                "--fs", str(args.fs),
                "--segment", str(args.segment),
            ]
            result = run_step(
                noise_cmd,
                f"[2/3] Noise Analysis ({noise_idx}/{total_noise}): {split}/{cls}",
            )
            noise_results[f"{split}/{cls}"] = result

            if result.returncode != 0:
                print(f"  WARNING: noise analysis failed for {split}/{cls}")

    # ── Step 3: Training & benchmarking ───────────────────────────────────
    bench_cmd = [
        sys.executable, str(SCRIPT_DIR / "benchmark.py"),
        "--data-dir", str(dataset_path),
        "--output-dir", str(output_dir / "benchmark"),
        "--dataset-name", args.dataset_name,
        "--run-id", args.run_id,
        "--epochs", str(args.epochs),
        "--batch-size", str(args.batch_size),
        "--lr", str(args.lr),
        "--patience", str(args.patience),
        "--seed", str(args.seed),
        "--scheduler", args.scheduler,
    ]
    if args.real_test_dir:
        bench_cmd += ["--real-test-dir", args.real_test_dir]
    if args.wandb_offline:
        bench_cmd.append("--wandb-offline")

    benchmark_result = run_step(bench_cmd, "[3/3] Training & Benchmark")

    # ── Step 4: Generate summary ──────────────────────────────────────────
    total_time = time.time() - pipeline_start
    write_summary(output_dir, args, class_names, leak_result, noise_results,
                  benchmark_result)

    # ── Final console output ──────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("  PIPELINE COMPLETE")
    print("=" * 60)

    noise_ok = sum(1 for r in noise_results.values() if r.returncode == 0)
    noise_fail = len(noise_results) - noise_ok

    print(f"  Leak detection:   PASSED")
    print(f"  Noise analysis:   {noise_ok}/{len(noise_results)} succeeded"
          + (f" ({noise_fail} failed)" if noise_fail else ""))
    if benchmark_result.returncode == 0:
        print(f"  Benchmark:        COMPLETED")
    else:
        print(f"  Benchmark:        FAILED (exit code {benchmark_result.returncode})")
    print(f"  Total time:       {total_time:.1f}s")
    print(f"  Results:          {output_dir.resolve()}/")
    print(f"  Summary:          {(output_dir / 'analysis_summary.md').resolve()}")
    print("=" * 60)


if __name__ == "__main__":
    main()
