"""Two-panel horizontal bar chart: before/after doublet accuracy + latency.

Reproduces ``results/doublet_3fam_retrained/doublet_comparison_acc_latency.pdf``:
    (a) doublet test accuracy — zoo baseline vs retrained
    (b) inference latency — baseline vs retrained

Fixes overlap between the (a)/(b) panel labels and the bars by placing the
labels OUTSIDE the data area (above each axes), and expands the bottom margin
so the shared legend no longer touches the x-axis title.
"""

import json
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from benchmark_zoo import FAMILY_COLORS, _emit_pdf  # noqa: E402
from p0.plotting import apply_publication_style, DCOL_W  # noqa: E402


# Accuracy values stay hardcoded — they come from the published doublet
# experiments and are stable. Latency values now come from
# ``_lat_comparison.json`` (CPU torch, batch=1) generated by
# ``scripts/remeasure_cpu_latency_doublet_3fam.py`` so they stay in sync
# with the canonical CPU convention (see ``doc/metrics_conventions.md``).
FAMILIES = ["EfficientNet1D", "ResNet1D", "Conv1DGAP"]  # bottom -> top
ACC_BEFORE = {"Conv1DGAP": 45.1, "ResNet1D": 48.9, "EfficientNet1D": 49.2}
ACC_AFTER  = {"Conv1DGAP": 92.8, "ResNet1D": 91.0, "EfficientNet1D": 90.7}

_LAT_CMP_JSON = Path("results/doublet_3fam_retrained/_lat_comparison.json")

BEFORE_COLOR = "0.75"


def _load_lat_comparison() -> tuple[dict, dict]:
    """Load LAT_BEFORE / LAT_AFTER from the CPU-measured comparison JSON.

    Generated by ``scripts/remeasure_cpu_latency_doublet_3fam.py``. If
    the JSON is missing, raises a clear error pointing the caller at
    the script that produces it.
    """
    if not _LAT_CMP_JSON.exists():
        raise FileNotFoundError(
            f"{_LAT_CMP_JSON} not found. Generate it first via:\n"
            f"  python scripts/remeasure_cpu_latency_doublet_3fam.py"
        )
    with open(_LAT_CMP_JSON) as f:
        data = json.load(f)
    return data["LAT_BEFORE"], data["LAT_AFTER"]


def _make_figure(lat_before: dict, lat_after: dict) -> plt.Figure:
    apply_publication_style()
    fig, (ax_acc, ax_lat) = plt.subplots(1, 2, figsize=(DCOL_W, 2.60))

    y = np.arange(len(FAMILIES))
    bar_h = 0.38

    # ── Panel (a): accuracy ────────────────────────────────────────────────
    for i, fam in enumerate(FAMILIES):
        col = FAMILY_COLORS.get(fam, "#333333")
        ax_acc.barh(y[i] + bar_h / 2, ACC_AFTER[fam],  height=bar_h,
                    color=col, edgecolor="none", zorder=3)
        ax_acc.barh(y[i] - bar_h / 2, ACC_BEFORE[fam], height=bar_h,
                    color=BEFORE_COLOR, edgecolor="none", zorder=3)

        delta = ACC_AFTER[fam] - ACC_BEFORE[fam]
        ax_acc.text(ACC_AFTER[fam] + 1.2, y[i] + bar_h / 2,
                    f"{ACC_AFTER[fam]:.1f}  (+{delta:.1f})",
                    va="center", ha="left", fontsize=7)
        ax_acc.text(ACC_BEFORE[fam] - 1.2, y[i] - bar_h / 2,
                    f"{ACC_BEFORE[fam]:.1f}",
                    va="center", ha="right", fontsize=7, color="0.35")

    ax_acc.set_yticks(y)
    ax_acc.set_yticklabels(
        FAMILIES,
        fontsize=8, fontweight="bold",
    )
    for tick_lbl, fam in zip(ax_acc.get_yticklabels(), FAMILIES):
        tick_lbl.set_color(FAMILY_COLORS.get(fam, "black"))

    ax_acc.set_xlim(35, 108)
    ax_acc.set_xlabel("Accuracy (%)")
    ax_acc.spines["top"].set_visible(False)
    ax_acc.spines["right"].set_visible(False)
    ax_acc.grid(True, axis="x", alpha=0.3, linewidth=0.4)
    ax_acc.set_axisbelow(True)

    # ── Panel (b): latency ─────────────────────────────────────────────────
    for i, fam in enumerate(FAMILIES):
        col = FAMILY_COLORS.get(fam, "#333333")
        ax_lat.barh(y[i] + bar_h / 2, lat_after[fam],  height=bar_h,
                    color=col, edgecolor="none", zorder=3)
        ax_lat.barh(y[i] - bar_h / 2, lat_before[fam], height=bar_h,
                    color=BEFORE_COLOR, edgecolor="none", zorder=3)

        slowdown = lat_after[fam] / lat_before[fam] if lat_before[fam] else 1.0
        ax_lat.text(lat_after[fam] * 1.08, y[i] + bar_h / 2,
                    f"{lat_after[fam]:.2f}  ({slowdown:.1f}x)",
                    va="center", ha="left", fontsize=7)
        ax_lat.text(lat_before[fam] / 1.08, y[i] - bar_h / 2,
                    f"{lat_before[fam]:.2f}",
                    va="center", ha="right", fontsize=7, color="0.35")

    ax_lat.set_yticks(y)
    ax_lat.set_yticklabels([])
    ax_lat.set_xscale("log")
    # Bounds derived from data: ~half a decade of headroom on each side so
    # the inline value labels (placed at lat * 1.08 / lat / 1.08) sit fully
    # inside the canvas.
    lat_lo = min(min(lat_before.values()), min(lat_after.values())) / 2.5
    lat_hi = max(max(lat_before.values()), max(lat_after.values())) * 2.5
    ax_lat.set_xlim(lat_lo, lat_hi)
    ax_lat.set_xlabel("Latency (ms) — CPU torch, batch = 1")
    ax_lat.spines["top"].set_visible(False)
    ax_lat.spines["right"].set_visible(False)
    ax_lat.grid(True, axis="x", which="both", alpha=0.3, linewidth=0.4)
    ax_lat.set_axisbelow(True)

    ax_lat.text(
        0.99, 0.01, "CPU torch, batch = 1",
        transform=ax_lat.transAxes, ha="right", va="bottom",
        fontsize=6, color="0.50", style="italic",
    )

    # ── (a) / (b) panel labels OUTSIDE data area (above each axes) ─────────
    #   Placed in figure coordinates so they don't overlap the top bar.
    ax_acc.text(0.0, 1.04, "(a)", transform=ax_acc.transAxes,
                ha="left", va="bottom", fontsize=9, fontweight="bold")
    ax_lat.text(0.0, 1.04, "(b)", transform=ax_lat.transAxes,
                ha="left", va="bottom", fontsize=9, fontweight="bold")

    # ── Shared legend at the very bottom ───────────────────────────────────
    before_patch = mpatches.Patch(facecolor=BEFORE_COLOR, edgecolor="none",
                                  label="Before (zoo, 625 samples)")
    after_patch = mpatches.Patch(facecolor="0.35", edgecolor="none",
                                 label="After (retrained, 4096 samples)")
    fig.legend(
        handles=[before_patch, after_patch],
        loc="lower center", ncol=2,
        frameon=False, bbox_to_anchor=(0.5, 0.0),
        fontsize=7, handlelength=1.4, columnspacing=2.0,
    )

    # Generous bottom margin so xlabel <-> legend don't touch; extra top
    # margin to host the (a)/(b) labels outside the axes.
    fig.subplots_adjust(
        left=0.17, right=0.97, top=0.90, bottom=0.24, wspace=0.08,
    )
    return fig


def main():
    out_dir = Path("results/doublet_3fam_retrained")
    out_dir.mkdir(parents=True, exist_ok=True)
    lat_before, lat_after = _load_lat_comparison()
    fig = _make_figure(lat_before, lat_after)
    _emit_pdf(
        fig, out_dir, "doublet_comparison_acc_latency.pdf",
        wandb_run=None,
        caption=(
            "Doublet test accuracy (a) and inference latency (b) before "
            "(zoo baseline, 625 samples) and after retraining "
            "(4096 samples) for three model families. Latency measured on "
            "CPU torch, batch=1."
        ),
    )
    print(f"Wrote {out_dir / 'doublet_comparison_acc_latency.pdf'}")


if __name__ == "__main__":
    main()
